version: 2
jobs:
  build:
    working_directory: ~/status-board
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Global Packages
          command: yarn global add npmvet nsp
      - run:
          name: Install Local Packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: NPM Vet
          command: yarn verify:npmvet
      - run:
          name: Node Security
          command: yarn verify:nsp
      - run:
          name: TSLint
          command: yarn tslint
      - run:
          name: Test with Code Coverage
          command: yarn test:coverage:ci
      - run:
          name: Build
          command: yarn ts:build
      - store_artifacts:
          path: test-report.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-report.xml