version: 2
jobs:
  build:
    working_directory: ~/status-board
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Global Packages
          command: yarn global add npmvet nsp
      - run:
          name: Install Local Packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create reports directory
          command: mkdir reports &&  mkdir reports/tslint
      - run:
          name: NPM Vet
          command: yarn verify:npmvet
      - run:
          name: Node Security
          command: yarn verify:nsp
      - run:
          name: TSLint
          command: yarn tslint
      - run:
          name: Test Suite
          environment:
            JEST_JUNIT_OUTPUT: reports/jest/jest-test-results.xml
          command: yarn test:ci
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Coverage
          command: |
            ./cc-test-reporter before-build
            yarn test:coverage:ci
            ./cc-test-reporter after-build --exit-code $?
            yarn test:coverage:codecov
      - run:
          name: Build JavaScript
          command: yarn ts:build
      - run:
          name: Semantic Release
          command: yarn semantic-release
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: reports/junit
      - store_test_results:
          path: reports